version: "3.7"

services:
    my-postgres:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - my-postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: testuser
            POSTGRES_PASSWORD: supersecret

    my-pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: test@gmail.com
            PGADMIN_DEFAULT_PASSWORD: supersecret

volumes:
    my-postgres-data: