version: "3.7"

services:
    my-postgres:
        build: .
        ports:
            - 5432:5432
        volumes:
            - my-postgres-data:/var/lib/postgresql/data
            - ./code:/code


    my-pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: test@gmail.com
            PGADMIN_DEFAULT_PASSWORD: supersecret

volumes:
    my-postgres-data:
